package database;

// Generated 1 avr. 2013 22:44:41 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AvoirPourPrefixeBase generated by hbm2java
 */
@Entity
@Table(name = "avoir_pour_prefixe_base", catalog = "bddictionnairique")
public class AvoirPourPrefixeBase implements java.io.Serializable {

	private static final long serialVersionUID = 7679901564792374691L;

	private AvoirPourPrefixeBaseId id;
	private ListeMorphemesPrefsuffbase listeMorphemesPrefsuffbase;
	private ListeCategories listeCategories;
	private String type;

	public AvoirPourPrefixeBase() {
	}

	public AvoirPourPrefixeBase(AvoirPourPrefixeBaseId id,
			ListeMorphemesPrefsuffbase listeMorphemesPrefsuffbase,
			ListeCategories listeCategories) {
		this.id = id;
		this.listeMorphemesPrefsuffbase = listeMorphemesPrefsuffbase;
		this.listeCategories = listeCategories;
	}

	public AvoirPourPrefixeBase(AvoirPourPrefixeBaseId id,
			ListeMorphemesPrefsuffbase listeMorphemesPrefsuffbase,
			ListeCategories listeCategories, String type) {
		this.id = id;
		this.listeMorphemesPrefsuffbase = listeMorphemesPrefsuffbase;
		this.listeCategories = listeCategories;
		this.type = type;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idCategorie", column = @Column(name = "id_categorie", nullable = false)),
			@AttributeOverride(name = "idMorphPrefsuffbase", column = @Column(name = "id_morph_prefsuffbase", nullable = false)) })
	public AvoirPourPrefixeBaseId getId() {
		return this.id;
	}

	public void setId(AvoirPourPrefixeBaseId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_morph_prefsuffbase", nullable = false, insertable = false, updatable = false)
	public ListeMorphemesPrefsuffbase getListeMorphemesPrefsuffbase() {
		return this.listeMorphemesPrefsuffbase;
	}

	public void setListeMorphemesPrefsuffbase(
			ListeMorphemesPrefsuffbase listeMorphemesPrefsuffbase) {
		this.listeMorphemesPrefsuffbase = listeMorphemesPrefsuffbase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_categorie", nullable = false, insertable = false, updatable = false)
	public ListeCategories getListeCategories() {
		return this.listeCategories;
	}

	public void setListeCategories(ListeCategories listeCategories) {
		this.listeCategories = listeCategories;
	}

	@Column(name = "type", length = 15)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
