package database;

// Generated 25 janv. 2013 00:04:50 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Composes generated by hbm2java
 */
@Entity
@Table(name = "composes", catalog = "bddictionnairique")
public class Composes implements java.io.Serializable {

	private Integer idCompose;
	private Headword headword;
	private String texte;

	public Composes() {
	}

	public Composes(Headword headword) {
		this.headword = headword;
	}

	public Composes(Headword headword, String texte) {
		this.headword = headword;
		this.texte = texte;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_compose", unique = true, nullable = false)
	public Integer getIdCompose() {
		return this.idCompose;
	}

	public void setIdCompose(Integer idCompose) {
		this.idCompose = idCompose;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_headword", nullable = false)
	public Headword getHeadword() {
		return this.headword;
	}

	public void setHeadword(Headword headword) {
		this.headword = headword;
	}

	@Column(name = "texte", length = 65535)
	public String getTexte() {
		return this.texte;
	}

	public void setTexte(String texte) {
		this.texte = texte;
	}

}
