package database;

// Generated 29 mars 2013 17:34:42 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DecompositionMorphologique generated by hbm2java
 */
@Entity
@Table(name = "decomposition_morphologique", catalog = "bddictionnairique")
public class DecompositionMorphologique implements java.io.Serializable {

	private static final long serialVersionUID = 5713094479186742895L;

	private Integer idMorph;
	private Headword headword;
	private TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph1;
	private TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph2;
	private TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph3;
	private TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph4;
	private TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph5;
	private TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph6;
	private TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph7;
	private TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph8;
	private TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph9;
	private TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph10;
	private String m1;
	private String m2;
	private String m3;
	private String m4;
	private String m5;
	private String m6;
	private String m7;
	private String m8;
	private String m9;
	private String m10;
	private String note;

	public DecompositionMorphologique() {
	}

	public DecompositionMorphologique(
			Headword headword,
			TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph1,
			TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph2,
			TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph3,
			TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph4,
			TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph5,
			TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph6,
			TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph7,
			TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph8,
			TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph9,
			TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph10) {
		this.headword = headword;
		this.typesMorphologieByTypesMorphologieIdTypeMorph1 = typesMorphologieByTypesMorphologieIdTypeMorph1;
		this.typesMorphologieByTypesMorphologieIdTypeMorph2 = typesMorphologieByTypesMorphologieIdTypeMorph2;
		this.typesMorphologieByTypesMorphologieIdTypeMorph3 = typesMorphologieByTypesMorphologieIdTypeMorph3;
		this.typesMorphologieByTypesMorphologieIdTypeMorph4 = typesMorphologieByTypesMorphologieIdTypeMorph4;
		this.typesMorphologieByTypesMorphologieIdTypeMorph5 = typesMorphologieByTypesMorphologieIdTypeMorph5;
		this.typesMorphologieByTypesMorphologieIdTypeMorph6 = typesMorphologieByTypesMorphologieIdTypeMorph6;
		this.typesMorphologieByTypesMorphologieIdTypeMorph7 = typesMorphologieByTypesMorphologieIdTypeMorph7;
		this.typesMorphologieByTypesMorphologieIdTypeMorph8 = typesMorphologieByTypesMorphologieIdTypeMorph8;
		this.typesMorphologieByTypesMorphologieIdTypeMorph9 = typesMorphologieByTypesMorphologieIdTypeMorph9;
		this.typesMorphologieByTypesMorphologieIdTypeMorph10 = typesMorphologieByTypesMorphologieIdTypeMorph10;
	}

	public DecompositionMorphologique(
			Headword headword,
			TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph1,
			TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph2,
			TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph3,
			TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph4,
			TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph5,
			TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph6,
			TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph7,
			TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph8,
			TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph9,
			TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph10,
			String m1, String m2, String m3, String m4, String m5, String m6,
			String m7, String m8, String m9, String m10, String note) {
		this.headword = headword;
		this.typesMorphologieByTypesMorphologieIdTypeMorph1 = typesMorphologieByTypesMorphologieIdTypeMorph1;
		this.typesMorphologieByTypesMorphologieIdTypeMorph2 = typesMorphologieByTypesMorphologieIdTypeMorph2;
		this.typesMorphologieByTypesMorphologieIdTypeMorph3 = typesMorphologieByTypesMorphologieIdTypeMorph3;
		this.typesMorphologieByTypesMorphologieIdTypeMorph4 = typesMorphologieByTypesMorphologieIdTypeMorph4;
		this.typesMorphologieByTypesMorphologieIdTypeMorph5 = typesMorphologieByTypesMorphologieIdTypeMorph5;
		this.typesMorphologieByTypesMorphologieIdTypeMorph6 = typesMorphologieByTypesMorphologieIdTypeMorph6;
		this.typesMorphologieByTypesMorphologieIdTypeMorph7 = typesMorphologieByTypesMorphologieIdTypeMorph7;
		this.typesMorphologieByTypesMorphologieIdTypeMorph8 = typesMorphologieByTypesMorphologieIdTypeMorph8;
		this.typesMorphologieByTypesMorphologieIdTypeMorph9 = typesMorphologieByTypesMorphologieIdTypeMorph9;
		this.typesMorphologieByTypesMorphologieIdTypeMorph10 = typesMorphologieByTypesMorphologieIdTypeMorph10;
		this.m1 = m1;
		this.m2 = m2;
		this.m3 = m3;
		this.m4 = m4;
		this.m5 = m5;
		this.m6 = m6;
		this.m7 = m7;
		this.m8 = m8;
		this.m9 = m9;
		this.m10 = m10;
		this.note = note;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_morph", unique = true, nullable = false)
	public Integer getIdMorph() {
		return this.idMorph;
	}

	public void setIdMorph(Integer idMorph) {
		this.idMorph = idMorph;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "types_morphologie_id_type_morph1", nullable = false)
	public TypesMorphologie getTypesMorphologieByTypesMorphologieIdTypeMorph1() {
		return this.typesMorphologieByTypesMorphologieIdTypeMorph1;
	}

	public void setTypesMorphologieByTypesMorphologieIdTypeMorph1(
			TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph1) {
		this.typesMorphologieByTypesMorphologieIdTypeMorph1 = typesMorphologieByTypesMorphologieIdTypeMorph1;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "headword_id_headword", nullable = false)
	public Headword getHeadword() {
		return this.headword;
	}

	public void setHeadword(Headword headword) {
		this.headword = headword;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "types_morphologie_id_type_morph5", nullable = false)
	public TypesMorphologie getTypesMorphologieByTypesMorphologieIdTypeMorph5() {
		return this.typesMorphologieByTypesMorphologieIdTypeMorph5;
	}

	public void setTypesMorphologieByTypesMorphologieIdTypeMorph5(
			TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph5) {
		this.typesMorphologieByTypesMorphologieIdTypeMorph5 = typesMorphologieByTypesMorphologieIdTypeMorph5;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "types_morphologie_id_type_morph7", nullable = false)
	public TypesMorphologie getTypesMorphologieByTypesMorphologieIdTypeMorph7() {
		return this.typesMorphologieByTypesMorphologieIdTypeMorph7;
	}

	public void setTypesMorphologieByTypesMorphologieIdTypeMorph7(
			TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph7) {
		this.typesMorphologieByTypesMorphologieIdTypeMorph7 = typesMorphologieByTypesMorphologieIdTypeMorph7;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "types_morphologie_id_type_morph4", nullable = false)
	public TypesMorphologie getTypesMorphologieByTypesMorphologieIdTypeMorph4() {
		return this.typesMorphologieByTypesMorphologieIdTypeMorph4;
	}

	public void setTypesMorphologieByTypesMorphologieIdTypeMorph4(
			TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph4) {
		this.typesMorphologieByTypesMorphologieIdTypeMorph4 = typesMorphologieByTypesMorphologieIdTypeMorph4;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "types_morphologie_id_type_morph6", nullable = false)
	public TypesMorphologie getTypesMorphologieByTypesMorphologieIdTypeMorph6() {
		return this.typesMorphologieByTypesMorphologieIdTypeMorph6;
	}

	public void setTypesMorphologieByTypesMorphologieIdTypeMorph6(
			TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph6) {
		this.typesMorphologieByTypesMorphologieIdTypeMorph6 = typesMorphologieByTypesMorphologieIdTypeMorph6;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "types_morphologie_id_type_morph9", nullable = false)
	public TypesMorphologie getTypesMorphologieByTypesMorphologieIdTypeMorph9() {
		return this.typesMorphologieByTypesMorphologieIdTypeMorph9;
	}

	public void setTypesMorphologieByTypesMorphologieIdTypeMorph9(
			TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph9) {
		this.typesMorphologieByTypesMorphologieIdTypeMorph9 = typesMorphologieByTypesMorphologieIdTypeMorph9;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "types_morphologie_id_type_morph10", nullable = false)
	public TypesMorphologie getTypesMorphologieByTypesMorphologieIdTypeMorph10() {
		return this.typesMorphologieByTypesMorphologieIdTypeMorph10;
	}

	public void setTypesMorphologieByTypesMorphologieIdTypeMorph10(
			TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph10) {
		this.typesMorphologieByTypesMorphologieIdTypeMorph10 = typesMorphologieByTypesMorphologieIdTypeMorph10;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "types_morphologie_id_type_morph3", nullable = false)
	public TypesMorphologie getTypesMorphologieByTypesMorphologieIdTypeMorph3() {
		return this.typesMorphologieByTypesMorphologieIdTypeMorph3;
	}

	public void setTypesMorphologieByTypesMorphologieIdTypeMorph3(
			TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph3) {
		this.typesMorphologieByTypesMorphologieIdTypeMorph3 = typesMorphologieByTypesMorphologieIdTypeMorph3;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "types_morphologie_id_type_morph8", nullable = false)
	public TypesMorphologie getTypesMorphologieByTypesMorphologieIdTypeMorph8() {
		return this.typesMorphologieByTypesMorphologieIdTypeMorph8;
	}

	public void setTypesMorphologieByTypesMorphologieIdTypeMorph8(
			TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph8) {
		this.typesMorphologieByTypesMorphologieIdTypeMorph8 = typesMorphologieByTypesMorphologieIdTypeMorph8;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "types_morphologie_id_type_morph2", nullable = false)
	public TypesMorphologie getTypesMorphologieByTypesMorphologieIdTypeMorph2() {
		return this.typesMorphologieByTypesMorphologieIdTypeMorph2;
	}

	public void setTypesMorphologieByTypesMorphologieIdTypeMorph2(
			TypesMorphologie typesMorphologieByTypesMorphologieIdTypeMorph2) {
		this.typesMorphologieByTypesMorphologieIdTypeMorph2 = typesMorphologieByTypesMorphologieIdTypeMorph2;
	}

	@Column(name = "m1", length = 15)
	public String getM1() {
		return this.m1;
	}

	public void setM1(String m1) {
		this.m1 = m1;
	}

	@Column(name = "m2", length = 15)
	public String getM2() {
		return this.m2;
	}

	public void setM2(String m2) {
		this.m2 = m2;
	}

	@Column(name = "m3", length = 15)
	public String getM3() {
		return this.m3;
	}

	public void setM3(String m3) {
		this.m3 = m3;
	}

	@Column(name = "m4", length = 15)
	public String getM4() {
		return this.m4;
	}

	public void setM4(String m4) {
		this.m4 = m4;
	}

	@Column(name = "m5", length = 15)
	public String getM5() {
		return this.m5;
	}

	public void setM5(String m5) {
		this.m5 = m5;
	}

	@Column(name = "m6", length = 15)
	public String getM6() {
		return this.m6;
	}

	public void setM6(String m6) {
		this.m6 = m6;
	}

	@Column(name = "m7", length = 15)
	public String getM7() {
		return this.m7;
	}

	public void setM7(String m7) {
		this.m7 = m7;
	}

	@Column(name = "m8", length = 15)
	public String getM8() {
		return this.m8;
	}

	public void setM8(String m8) {
		this.m8 = m8;
	}

	@Column(name = "m9", length = 15)
	public String getM9() {
		return this.m9;
	}

	public void setM9(String m9) {
		this.m9 = m9;
	}

	@Column(name = "m10", length = 15)
	public String getM10() {
		return this.m10;
	}

	public void setM10(String m10) {
		this.m10 = m10;
	}

	@Column(name = "note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
