package database;

// Generated 29 mars 2013 17:34:42 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dictionnaires generated by hbm2java
 */
@Entity
@Table(name = "dictionnaires", catalog = "bddictionnairique")
public class Dictionnaires implements java.io.Serializable {

	private static final long serialVersionUID = 7875412124961823995L;

	private Integer idDictionnaire;
	private String nomDictionnaire;
	private Set<Headword> headwords = new HashSet<Headword>(0);

	public Dictionnaires() {
	}

	public Dictionnaires(String nomDictionnaire, Set<Headword> headwords) {
		this.nomDictionnaire = nomDictionnaire;
		this.headwords = headwords;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_dictionnaire", unique = true, nullable = false)
	public Integer getIdDictionnaire() {
		return this.idDictionnaire;
	}

	public void setIdDictionnaire(Integer idDictionnaire) {
		this.idDictionnaire = idDictionnaire;
	}

	@Column(name = "nom_dictionnaire", length = 20)
	public String getNomDictionnaire() {
		return this.nomDictionnaire;
	}

	public void setNomDictionnaire(String nomDictionnaire) {
		this.nomDictionnaire = nomDictionnaire;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dictionnaires")
	public Set<Headword> getHeadwords() {
		return this.headwords;
	}

	public void setHeadwords(Set<Headword> headwords) {
		this.headwords = headwords;
	}

}
