package database;

// Generated 25 janv. 2013 00:04:50 by Hibernate Tools 3.4.0.CR1

import java.awt.event.MouseEvent;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dictionnaires generated by hbm2java
 */
@Entity
@Table(name = "dictionnaires", catalog = "bddictionnairique")
public class Dictionnaires implements java.io.Serializable {

	private Integer idDictionnaire;
	private String nomDictionnaire;
	private Set syllabeses = new HashSet(0);
	private Set headwords = new HashSet(0);
	private Set flexionses = new HashSet(0);

	public Dictionnaires() {
	}

	public Dictionnaires(String nomDictionnaire, Set syllabeses, Set headwords,
			Set flexionses) {
		this.nomDictionnaire = nomDictionnaire;
		this.syllabeses = syllabeses;
		this.headwords = headwords;
		this.flexionses = flexionses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_dictionnaire", unique = true, nullable = false)
	public Integer getIdDictionnaire() {
		return this.idDictionnaire;
	}

	public void setIdDictionnaire(Integer idDictionnaire) {
		this.idDictionnaire = idDictionnaire;
	}

	@Column(name = "nom_dictionnaire", length = 20)
	public String getNomDictionnaire() {
		return this.nomDictionnaire;
	}

	public void setNomDictionnaire(String nomDictionnaire) {
		this.nomDictionnaire = nomDictionnaire;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dictionnaires")
	public Set getSyllabeses() {
		return this.syllabeses;
	}

	public void setSyllabeses(Set syllabeses) {
		this.syllabeses = syllabeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dictionnaires")
	public Set getHeadwords() {
		return this.headwords;
	}

	public void setHeadwords(Set headwords) {
		this.headwords = headwords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dictionnaires")
	public Set getFlexionses() {
		return this.flexionses;
	}

	public void setFlexionses(Set flexionses) {
		this.flexionses = flexionses;
	}
}
