package database;

// Generated 25 janv. 2013 00:04:50 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EtymoMcq generated by hbm2java
 */
@Entity
@Table(name = "etymo_mcq", catalog = "bddictionnairique")
public class EtymoMcq implements java.io.Serializable {

	private Integer idEtymo;
	private Headword headword;
	private String date;
	private String langue;
	private String contenu;
	private Integer flag;

	public EtymoMcq() {
	}

	public EtymoMcq(Headword headword) {
		this.headword = headword;
	}

	public EtymoMcq(Headword headword, String date, String langue,
			String contenu, Integer flag) {
		this.headword = headword;
		this.date = date;
		this.langue = langue;
		this.contenu = contenu;
		this.flag = flag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_etymo", unique = true, nullable = false)
	public Integer getIdEtymo() {
		return this.idEtymo;
	}

	public void setIdEtymo(Integer idEtymo) {
		this.idEtymo = idEtymo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_headword", nullable = false)
	public Headword getHeadword() {
		return this.headword;
	}

	public void setHeadword(Headword headword) {
		this.headword = headword;
	}

	@Column(name = "date", length = 15)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "langue", length = 25)
	public String getLangue() {
		return this.langue;
	}

	public void setLangue(String langue) {
		this.langue = langue;
	}

	@Column(name = "contenu", length = 65535)
	public String getContenu() {
		return this.contenu;
	}

	public void setContenu(String contenu) {
		this.contenu = contenu;
	}

	@Column(name = "flag")
	public Integer getFlag() {
		return this.flag;
	}

	public void setFlag(Integer flag) {
		this.flag = flag;
	}

}
