package database;

// Generated 29 mars 2013 17:34:42 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Flexions generated by hbm2java
 */
@Entity
@Table(name = "flexions", catalog = "bddictionnairique")
public class Flexions implements java.io.Serializable {

	private static final long serialVersionUID = 5039661337175167212L;

	private Integer idFlexion;
	private Headword headword;
	private String mot;
	private Set<Syllabes> syllabeses = new HashSet<Syllabes>(0);

	public Flexions() {
	}

	public Flexions(Headword headword) {
		this.headword = headword;
	}

	public Flexions(Headword headword, String mot, Set<Syllabes> syllabeses) {
		this.headword = headword;
		this.mot = mot;
		this.syllabeses = syllabeses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_flexion", unique = true, nullable = false)
	public Integer getIdFlexion() {
		return this.idFlexion;
	}

	public void setIdFlexion(Integer idFlexion) {
		this.idFlexion = idFlexion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_headword", nullable = false)
	public Headword getHeadword() {
		return this.headword;
	}

	public void setHeadword(Headword headword) {
		this.headword = headword;
	}

	@Column(name = "mot", length = 100)
	public String getMot() {
		return this.mot;
	}

	public void setMot(String mot) {
		this.mot = mot;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flexions")
	public Set<Syllabes> getSyllabeses() {
		return this.syllabeses;
	}

	public void setSyllabeses(Set<Syllabes> syllabeses) {
		this.syllabeses = syllabeses;
	}

}
