package database;

// Generated 23 janv. 2013 18:39:10 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Flexions generated by hbm2java
 */
@Entity
@Table(name = "flexions", catalog = "bddictionnairique")
public class Flexions implements java.io.Serializable {

	private Integer idFlexion;
	private Headword headword;
	private Dictionnaires dictionnaires;
	private String mot;
	private Set syllabeses = new HashSet(0);

	public Flexions() {
	}

	public Flexions(Headword headword, Dictionnaires dictionnaires) {
		this.headword = headword;
		this.dictionnaires = dictionnaires;
	}

	public Flexions(Headword headword, Dictionnaires dictionnaires, String mot,
			Set syllabeses) {
		this.headword = headword;
		this.dictionnaires = dictionnaires;
		this.mot = mot;
		this.syllabeses = syllabeses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_flexion", unique = true, nullable = false)
	public Integer getIdFlexion() {
		return this.idFlexion;
	}

	public void setIdFlexion(Integer idFlexion) {
		this.idFlexion = idFlexion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_headword", nullable = false)
	public Headword getHeadword() {
		return this.headword;
	}

	public void setHeadword(Headword headword) {
		this.headword = headword;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_dictionnaire", nullable = false)
	public Dictionnaires getDictionnaires() {
		return this.dictionnaires;
	}

	public void setDictionnaires(Dictionnaires dictionnaires) {
		this.dictionnaires = dictionnaires;
	}

	@Column(name = "mot", length = 100)
	public String getMot() {
		return this.mot;
	}

	public void setMot(String mot) {
		this.mot = mot;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flexions")
	public Set getSyllabeses() {
		return this.syllabeses;
	}

	public void setSyllabeses(Set syllabeses) {
		this.syllabeses = syllabeses;
	}

}
