package database;

// Generated 25 janv. 2013 00:04:50 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Frequence generated by hbm2java
 */
@Entity
@Table(name = "frequence", catalog = "bddictionnairique")
public class Frequence implements java.io.Serializable {

	private Integer idFreq;
	private SourceFrequence sourceFrequence;
	private LiensDict liensDict;
	private Double frequence;
	private String note;

	public Frequence() {
	}

	public Frequence(SourceFrequence sourceFrequence, LiensDict liensDict) {
		this.sourceFrequence = sourceFrequence;
		this.liensDict = liensDict;
	}

	public Frequence(SourceFrequence sourceFrequence, LiensDict liensDict,
			Double frequence, String note) {
		this.sourceFrequence = sourceFrequence;
		this.liensDict = liensDict;
		this.frequence = frequence;
		this.note = note;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_freq", unique = true, nullable = false)
	public Integer getIdFreq() {
		return this.idFreq;
	}

	public void setIdFreq(Integer idFreq) {
		this.idFreq = idFreq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_source_freq", nullable = false)
	public SourceFrequence getSourceFrequence() {
		return this.sourceFrequence;
	}

	public void setSourceFrequence(SourceFrequence sourceFrequence) {
		this.sourceFrequence = sourceFrequence;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_lien_dict", nullable = false)
	public LiensDict getLiensDict() {
		return this.liensDict;
	}

	public void setLiensDict(LiensDict liensDict) {
		this.liensDict = liensDict;
	}

	@Column(name = "frequence", precision = 22, scale = 0)
	public Double getFrequence() {
		return this.frequence;
	}

	public void setFrequence(Double frequence) {
		this.frequence = frequence;
	}

	@Column(name = "note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
