package database;

// Generated 29 mars 2013 17:34:42 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ListeUsages generated by hbm2java
 */
@Entity
@Table(name = "liste_usages", catalog = "bddictionnairique")
public class ListeUsages implements java.io.Serializable {

	private static final long serialVersionUID = -8216398577721972697L;

	private Integer idUsage;
	private Headword headword;
	private String usage;
	private String note;

	public ListeUsages() {
	}

	public ListeUsages(Headword headword) {
		this.headword = headword;
	}

	public ListeUsages(Headword headword, String usage, String note) {
		this.headword = headword;
		this.usage = usage;
		this.note = note;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_usage", unique = true, nullable = false)
	public Integer getIdUsage() {
		return this.idUsage;
	}

	public void setIdUsage(Integer idUsage) {
		this.idUsage = idUsage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "headword_id_headword", nullable = false)
	public Headword getHeadword() {
		return this.headword;
	}

	public void setHeadword(Headword headword) {
		this.headword = headword;
	}

	@Column(name = "usage", length = 15)
	public String getUsage() {
		return this.usage;
	}

	public void setUsage(String usage) {
		this.usage = usage;
	}

	@Column(name = "note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
