package database;

// Generated 23 janv. 2013 18:39:10 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ListeUsages generated by hbm2java
 */
@Entity
@Table(name = "liste_usages", catalog = "bddictionnairique")
public class ListeUsages implements java.io.Serializable {

	private Integer idUsage;
	private String usage;
	private Set usageLiens = new HashSet(0);

	public ListeUsages() {
	}

	public ListeUsages(String usage, Set usageLiens) {
		this.usage = usage;
		this.usageLiens = usageLiens;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_usage", unique = true, nullable = false)
	public Integer getIdUsage() {
		return this.idUsage;
	}

	public void setIdUsage(Integer idUsage) {
		this.idUsage = idUsage;
	}

	@Column(name = "usage", length = 15)
	public String getUsage() {
		return this.usage;
	}

	public void setUsage(String usage) {
		this.usage = usage;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "listeUsages")
	public Set getUsageLiens() {
		return this.usageLiens;
	}

	public void setUsageLiens(Set usageLiens) {
		this.usageLiens = usageLiens;
	}

}
