package database;

// Generated 23 janv. 2013 18:39:10 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ListeAllomorphes generated by hbm2java
 */
@Entity
@Table(name = "liste_allomorphes", catalog = "bddictionnairique")
public class ListeAllomorphes implements java.io.Serializable {

	private Integer idAllo;
	private ListeMorphemesPrefsuffbase listeMorphemesPrefsuffbase;
	private String type;
	private String contenu;
	private Double actif;

	public ListeAllomorphes() {
	}

	public ListeAllomorphes(
			ListeMorphemesPrefsuffbase listeMorphemesPrefsuffbase, String type,
			String contenu, Double actif) {
		this.listeMorphemesPrefsuffbase = listeMorphemesPrefsuffbase;
		this.type = type;
		this.contenu = contenu;
		this.actif = actif;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_allo", unique = true, nullable = false)
	public Integer getIdAllo() {
		return this.idAllo;
	}

	public void setIdAllo(Integer idAllo) {
		this.idAllo = idAllo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_morph_prefsuffbase")
	public ListeMorphemesPrefsuffbase getListeMorphemesPrefsuffbase() {
		return this.listeMorphemesPrefsuffbase;
	}

	public void setListeMorphemesPrefsuffbase(
			ListeMorphemesPrefsuffbase listeMorphemesPrefsuffbase) {
		this.listeMorphemesPrefsuffbase = listeMorphemesPrefsuffbase;
	}

	@Column(name = "type", length = 25)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "contenu", length = 50)
	public String getContenu() {
		return this.contenu;
	}

	public void setContenu(String contenu) {
		this.contenu = contenu;
	}

	@Column(name = "actif", precision = 22, scale = 0)
	public Double getActif() {
		return this.actif;
	}

	public void setActif(Double actif) {
		this.actif = actif;
	}

}
