package database;

// Generated 1 avr. 2013 22:44:41 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ListeStatuts generated by hbm2java
 */
@Entity
@Table(name = "liste_statuts", catalog = "bddictionnairique")
public class ListeStatuts implements java.io.Serializable {

	private static final long serialVersionUID = -4301196065640790304L;

	private Integer idStatut;
	private String statut;
	private Set<Lexique> lexiques = new HashSet<Lexique>(0);

	public ListeStatuts() {
	}

	public ListeStatuts(String statut, Set<Lexique> lexiques) {
		this.statut = statut;
		this.lexiques = lexiques;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_statut", unique = true, nullable = false)
	public Integer getIdStatut() {
		return this.idStatut;
	}

	public void setIdStatut(Integer idStatut) {
		this.idStatut = idStatut;
	}

	@Column(name = "statut", length = 15)
	public String getStatut() {
		return this.statut;
	}

	public void setStatut(String statut) {
		this.statut = statut;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "listeStatuts")
	public Set<Lexique> getLexiques() {
		return this.lexiques;
	}

	public void setLexiques(Set<Lexique> lexiques) {
		this.lexiques = lexiques;
	}

}
