package database;

// Generated 1 avr. 2013 22:44:41 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Note generated by hbm2java
 */
@Entity
@Table(name = "note", catalog = "bddictionnairique")
public class Note implements java.io.Serializable {

	private static final long serialVersionUID = -2782432649653589716L;

	private Integer idNote;
	private String texte;
	private Set<Headword> headwords = new HashSet<Headword>(0);

	public Note() {
	}

	public Note(String texte, Set<Headword> headwords) {
		this.texte = texte;
		this.headwords = headwords;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_note", unique = true, nullable = false)
	public Integer getIdNote() {
		return this.idNote;
	}

	public void setIdNote(Integer idNote) {
		this.idNote = idNote;
	}

	@Column(name = "texte", length = 65535)
	public String getTexte() {
		return this.texte;
	}

	public void setTexte(String texte) {
		this.texte = texte;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "note")
	public Set<Headword> getHeadwords() {
		return this.headwords;
	}

	public void setHeadwords(Set<Headword> headwords) {
		this.headwords = headwords;
	}

}
