package database;

// Generated 29 mars 2013 17:34:42 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Notes generated by hbm2java
 */
@Entity
@Table(name = "notes", catalog = "bddictionnairique")
public class Notes implements java.io.Serializable {

	private static final long serialVersionUID = 1678223507937655110L;

	private Integer idNotes;
	private String texte;
	private Set<Headword> headwords = new HashSet<Headword>(0);

	public Notes() {
	}

	public Notes(String texte, Set<Headword> headwords) {
		this.texte = texte;
		this.headwords = headwords;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_notes", unique = true, nullable = false)
	public Integer getIdNotes() {
		return this.idNotes;
	}

	public void setIdNotes(Integer idNotes) {
		this.idNotes = idNotes;
	}

	@Column(name = "texte", length = 65535)
	public String getTexte() {
		return this.texte;
	}

	public void setTexte(String texte) {
		this.texte = texte;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "notes")
	public Set<Headword> getHeadwords() {
		return this.headwords;
	}

	public void setHeadwords(Set<Headword> headwords) {
		this.headwords = headwords;
	}

}
