package database;

// Generated 1 avr. 2013 22:44:41 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Sens generated by hbm2java
 */
@Entity
@Table(name = "sens", catalog = "bddictionnairique")
public class Sens implements java.io.Serializable {

	private static final long serialVersionUID = -8723472776042416823L;

	private Integer idSens;
	private Headword headword;
	private String texte;
	private String origine;

	public Sens() {
	}

	public Sens(Headword headword) {
		this.headword = headword;
	}

	public Sens(Headword headword, String texte, String origine) {
		this.headword = headword;
		this.texte = texte;
		this.origine = origine;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_sens", unique = true, nullable = false)
	public Integer getIdSens() {
		return this.idSens;
	}

	public void setIdSens(Integer idSens) {
		this.idSens = idSens;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_headword", nullable = false)
	public Headword getHeadword() {
		return this.headword;
	}

	public void setHeadword(Headword headword) {
		this.headword = headword;
	}

	@Column(name = "texte", length = 65535)
	public String getTexte() {
		return this.texte;
	}

	public void setTexte(String texte) {
		this.texte = texte;
	}

	@Column(name = "origine", length = 10)
	public String getOrigine() {
		return this.origine;
	}

	public void setOrigine(String origine) {
		this.origine = origine;
	}

}
