package database;

// Generated 23 janv. 2013 18:39:10 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SourceFrequence generated by hbm2java
 */
@Entity
@Table(name = "source_frequence", catalog = "bddictionnairique")
public class SourceFrequence implements java.io.Serializable {

	private Integer idSourceFreq;
	private String source;
	private Set frequences = new HashSet(0);

	public SourceFrequence() {
	}

	public SourceFrequence(String source, Set frequences) {
		this.source = source;
		this.frequences = frequences;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_source_freq", unique = true, nullable = false)
	public Integer getIdSourceFreq() {
		return this.idSourceFreq;
	}

	public void setIdSourceFreq(Integer idSourceFreq) {
		this.idSourceFreq = idSourceFreq;
	}

	@Column(name = "source", length = 50)
	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sourceFrequence")
	public Set getFrequences() {
		return this.frequences;
	}

	public void setFrequences(Set frequences) {
		this.frequences = frequences;
	}

}
