package database;

// Generated 29 mars 2013 17:34:42 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Syllabes generated by hbm2java
 */
@Entity
@Table(name = "syllabes", catalog = "bddictionnairique")
public class Syllabes implements java.io.Serializable {

	private static final long serialVersionUID = 3606104368450571717L;

	private Integer idSyllabe;
	private Headword headword;
	private Flexions flexions;
	private Integer ordre;
	private String region;
	private String schema;
	private Integer nbSyllabes;
	private String typePrononciation;
	private String syllabe1;
	private String syllabe2;
	private String syllabe3;
	private String syllabe4;
	private String syllabe5;
	private String syllabe6;
	private String syllabe7;
	private String syllabe8;
	private String syllabe9;
	private String syllabe10;
	private String note;
	private String schemaPhonologique;
	private String catdefMot;

	public Syllabes() {
	}

	public Syllabes(Headword headword, Flexions flexions) {
		this.headword = headword;
		this.flexions = flexions;
	}

	public Syllabes(Headword headword, Flexions flexions, Integer ordre,
			String region, String schema, Integer nbSyllabes,
			String typePrononciation, String syllabe1, String syllabe2,
			String syllabe3, String syllabe4, String syllabe5, String syllabe6,
			String syllabe7, String syllabe8, String syllabe9,
			String syllabe10, String note, String schemaPhonologique,
			String catdefMot) {
		this.headword = headword;
		this.flexions = flexions;
		this.ordre = ordre;
		this.region = region;
		this.schema = schema;
		this.nbSyllabes = nbSyllabes;
		this.typePrononciation = typePrononciation;
		this.syllabe1 = syllabe1;
		this.syllabe2 = syllabe2;
		this.syllabe3 = syllabe3;
		this.syllabe4 = syllabe4;
		this.syllabe5 = syllabe5;
		this.syllabe6 = syllabe6;
		this.syllabe7 = syllabe7;
		this.syllabe8 = syllabe8;
		this.syllabe9 = syllabe9;
		this.syllabe10 = syllabe10;
		this.note = note;
		this.schemaPhonologique = schemaPhonologique;
		this.catdefMot = catdefMot;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_syllabe", unique = true, nullable = false)
	public Integer getIdSyllabe() {
		return this.idSyllabe;
	}

	public void setIdSyllabe(Integer idSyllabe) {
		this.idSyllabe = idSyllabe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_headword", nullable = false)
	public Headword getHeadword() {
		return this.headword;
	}

	public void setHeadword(Headword headword) {
		this.headword = headword;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_flexion", nullable = false)
	public Flexions getFlexions() {
		return this.flexions;
	}

	public void setFlexions(Flexions flexions) {
		this.flexions = flexions;
	}

	@Column(name = "ordre")
	public Integer getOrdre() {
		return this.ordre;
	}

	public void setOrdre(Integer ordre) {
		this.ordre = ordre;
	}

	@Column(name = "region", length = 50)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "schema", length = 20)
	public String getSchema() {
		return this.schema;
	}

	public void setSchema(String schema) {
		this.schema = schema;
	}

	@Column(name = "nb_syllabes")
	public Integer getNbSyllabes() {
		return this.nbSyllabes;
	}

	public void setNbSyllabes(Integer nbSyllabes) {
		this.nbSyllabes = nbSyllabes;
	}

	@Column(name = "type_prononciation", length = 15)
	public String getTypePrononciation() {
		return this.typePrononciation;
	}

	public void setTypePrononciation(String typePrononciation) {
		this.typePrononciation = typePrononciation;
	}

	@Column(name = "syllabe1", length = 25)
	public String getSyllabe1() {
		return this.syllabe1;
	}

	public void setSyllabe1(String syllabe1) {
		this.syllabe1 = syllabe1;
	}

	@Column(name = "syllabe2", length = 25)
	public String getSyllabe2() {
		return this.syllabe2;
	}

	public void setSyllabe2(String syllabe2) {
		this.syllabe2 = syllabe2;
	}

	@Column(name = "syllabe3", length = 25)
	public String getSyllabe3() {
		return this.syllabe3;
	}

	public void setSyllabe3(String syllabe3) {
		this.syllabe3 = syllabe3;
	}

	@Column(name = "syllabe4", length = 25)
	public String getSyllabe4() {
		return this.syllabe4;
	}

	public void setSyllabe4(String syllabe4) {
		this.syllabe4 = syllabe4;
	}

	@Column(name = "syllabe5", length = 25)
	public String getSyllabe5() {
		return this.syllabe5;
	}

	public void setSyllabe5(String syllabe5) {
		this.syllabe5 = syllabe5;
	}

	@Column(name = "syllabe6", length = 25)
	public String getSyllabe6() {
		return this.syllabe6;
	}

	public void setSyllabe6(String syllabe6) {
		this.syllabe6 = syllabe6;
	}

	@Column(name = "syllabe7", length = 25)
	public String getSyllabe7() {
		return this.syllabe7;
	}

	public void setSyllabe7(String syllabe7) {
		this.syllabe7 = syllabe7;
	}

	@Column(name = "syllabe8", length = 25)
	public String getSyllabe8() {
		return this.syllabe8;
	}

	public void setSyllabe8(String syllabe8) {
		this.syllabe8 = syllabe8;
	}

	@Column(name = "syllabe9", length = 25)
	public String getSyllabe9() {
		return this.syllabe9;
	}

	public void setSyllabe9(String syllabe9) {
		this.syllabe9 = syllabe9;
	}

	@Column(name = "syllabe10", length = 25)
	public String getSyllabe10() {
		return this.syllabe10;
	}

	public void setSyllabe10(String syllabe10) {
		this.syllabe10 = syllabe10;
	}

	@Column(name = "note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "schema_phonologique", length = 20)
	public String getSchemaPhonologique() {
		return this.schemaPhonologique;
	}

	public void setSchemaPhonologique(String schemaPhonologique) {
		this.schemaPhonologique = schemaPhonologique;
	}

	@Column(name = "catdef_mot", length = 50)
	public String getCatdefMot() {
		return this.catdefMot;
	}

	public void setCatdefMot(String catdefMot) {
		this.catdefMot = catdefMot;
	}

}
