package database;

// Generated 25 janv. 2013 00:04:50 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TypesConstruction generated by hbm2java
 */
@Entity
@Table(name = "types_construction", catalog = "bddictionnairique")
public class TypesConstruction implements java.io.Serializable {

	private Integer idConstruction;
	private String nom;
	private Set lexiques = new HashSet(0);

	public TypesConstruction() {
	}

	public TypesConstruction(String nom, Set lexiques) {
		this.nom = nom;
		this.lexiques = lexiques;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_construction", unique = true, nullable = false)
	public Integer getIdConstruction() {
		return this.idConstruction;
	}

	public void setIdConstruction(Integer idConstruction) {
		this.idConstruction = idConstruction;
	}

	@Column(name = "nom", length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typesConstruction")
	public Set getLexiques() {
		return this.lexiques;
	}

	public void setLexiques(Set lexiques) {
		this.lexiques = lexiques;
	}

}
