package database;

// Generated 23 janv. 2013 18:39:10 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsageLien generated by hbm2java
 */
@Entity
@Table(name = "usage_lien", catalog = "bddictionnairique")
public class UsageLien implements java.io.Serializable {

	private Integer idUsageLien;
	private ListeUsages listeUsages;
	private LiensDict liensDict;

	public UsageLien() {
	}

	public UsageLien(ListeUsages listeUsages, LiensDict liensDict) {
		this.listeUsages = listeUsages;
		this.liensDict = liensDict;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_usage_lien", unique = true, nullable = false)
	public Integer getIdUsageLien() {
		return this.idUsageLien;
	}

	public void setIdUsageLien(Integer idUsageLien) {
		this.idUsageLien = idUsageLien;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usage", nullable = false)
	public ListeUsages getListeUsages() {
		return this.listeUsages;
	}

	public void setListeUsages(ListeUsages listeUsages) {
		this.listeUsages = listeUsages;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_lien_dict", nullable = false)
	public LiensDict getLiensDict() {
		return this.liensDict;
	}

	public void setLiensDict(LiensDict liensDict) {
		this.liensDict = liensDict;
	}

}
