package database;

// Generated 29 mars 2013 17:34:42 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Utilisateurs generated by hbm2java
 */
@Entity
@Table(name = "Utilisateurs", catalog = "bddictionnairique")
public class Utilisateurs implements java.io.Serializable {

	private static final long serialVersionUID = -4642015143750240626L;

	private Integer idUtilisateur;
	private String nom;
	private String login;
	private String password;
	private boolean admin;

	public Utilisateurs() {
	}

	public Utilisateurs(boolean admin) {
		this.admin = admin;
	}

	public Utilisateurs(String nom, String login, String password, boolean admin) {
		this.nom = nom;
		this.login = login;
		this.password = password;
		this.admin = admin;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_utilisateur", unique = true, nullable = false)
	public Integer getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(Integer idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	@Column(name = "nom", length = 45)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "login", length = 45)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "password", length = 65535)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "admin", nullable = false)
	public boolean isAdmin() {
		return this.admin;
	}

	public void setAdmin(boolean admin) {
		this.admin = admin;
	}

}
